[package]
name = "ram-vban"
description = "VBAN protocol implementation for AudioMatrix"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ram-core = { path = "../ram-core" }
socket2.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true

[dev-dependencies]
proptest.workspace = true
